/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package release.savepoint;

import java.sql.*;
import java.util.Properties;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void appHasAGreeting() throws SQLException {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:postgresql://localhost:5431/postgres");
        config.setUsername("postgres");
        config.setPassword("postgres");

        HikariDataSource ds = new HikariDataSource(config);
        try (Connection conn = ds.getConnection()) {

            conn.setAutoCommit(false);
            Savepoint savepoint = conn.setSavepoint();

            try (Statement statement = conn.createStatement()) {
                try (ResultSet rs = statement.executeQuery("select 'hi'")) {
                    if (rs.next())
                        System.out.println("Get String: " + rs.getString(1));
                }
            }

            conn.releaseSavepoint(savepoint);

            try (Statement statement = conn.createStatement()) {
                try (ResultSet rs = statement.executeQuery("select 'hello'")) {
                    if (rs.next())
                        System.out.println("Get String: " + rs.getString(1));
                }
            }
        }
    }
}
